name: Build and Deploy Docker Image to Docker Hub

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master 

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Specifies the runner environment.
    
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Sets up Docker Buildx to build multi-platform images.

    - name: Log in to Docker Hub
      uses: docker/login-action@v1  # Logs in to Docker Hub using the secrets stored in the GitHub repository.
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v2  # Builds the Docker image and pushes it to Docker Hub.
      with:
        context: .  # Path to the Dockerfile and the root of the context.
        file: ./Dockerfile  # Location of the Dockerfile.
        push: true  # Ensures the image is pushed to Docker Hub after being built.
        tags: senthilnasa/zktecho-api:latest  # Tags the image.

